# fly.toml app configuration file generated for rasende2-frontend on 2024-08-24T16:11:40+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rasende2-frontend'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

# NOTE: machine does not start when using fly io internal url, i.e. 'http://rasende2-api.internal'
[env]
  NEXT_PUBLIC_API_URL=https://rasende2-api.bjarke.xyz
  NEXT_PUBLIC_INTENRAL_API_URL=https://rasende2-api.bjarke.xyz
  NEXT_PUBLIC_BASE_URL=https://rasende.bjarke.xyz